name: publish release
on:
    push:
        branches:
            - "main"
jobs:
    publish-to-github-package:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v4
            - name: Build image
              run: docker build . --file Dockerfile --tag docker-android --label "runnumber=${GITHUB_RUN_ID}"
            - name: Log in to registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            - name: Push image
              run: |
                  IMAGE_ID=$(echo "ghcr.io/${{ github.repository_owner }}/docker-android" | tr '[A-Z]' '[a-z]')
                  docker tag docker-android $IMAGE_ID:${{github.ref_name}}
                  docker push $IMAGE_ID:${{github.ref_name}}
                  docker tag docker-android $IMAGE_ID:latest
                  docker push $IMAGE_ID:latest
